In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("history.csv")

/var/folders/xp/pns_c2r97xn7m5lw5_1_d9q00000gn/T/ipykernel_50758/3951251560.py:1: DtypeWarning: Columns (87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("history.csv")

In [15]:
df = df.iloc[:, 53:78]
df.head()

,esir_number,shareholder_language,dup_trip_quad_code,special_tag,conjunction,title,function_code,tms_settlement_location,portfolio_cost_method,portfolio_name_address_option,...,has_discrete_auth,last_update_date,is_non_objecting_beneficial_owner,is_objecting_to_disclose_info,mailing_consent,consent_to_pay_for_mail,consent_to_email_delivery,has_received_instruction,risk_tolerance,investment_objective
0,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,f,NaN,f,f,0.0,f,f,f,NaN,NaN
1,NaN,NaN,A,NaN,NaN,MR,NaN,NaN,0.0,0.0,...,f,2022-09-08,t,f,0.0,f,f,t,H10M90,B05G85S10
2,NaN,F,A,NaN,NaN,MADAME,NaN,NaN,0.0,0.0,...,f,2014-04-23,f,t,0.0,t,f,t,H50M50S00,G50S50
3,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,f,2021-01-04,t,f,0.0,f,f,t,M99,G99
4,NaN,NaN,A,NaN,NaN,MRS,NaN,NaN,0.0,0.0,...,NaN,2017-07-24,f,t,0.0,f,f,t,M99,G99

In [16]:
def drop_cols(df, cols):
    df = df.drop(cols, axis=1)
    return df

In [17]:
def boolean_map(df, cols):
    for col in cols:
        df[col] = df[col].fillna('f').map({'t': 1, 'f': 0})
    return df

In [18]:
# Commentary: Standardized value from 0 to 1. Filled blanks with 0.
def parse_time(df, cols):
    for col in cols:
        df[col] = pd.to_datetime(df[col])
        min_date = df[col].min()
        df[col] = df[col].fillna(min_date)

        df[col] = df[col].astype(int)
        min = df[col].min()
        max = df[col].max()    
        df[col] = (df[col] - min) / (max - min)

    return df

In [19]:
# 1. Drop Useless
drop_columns = ['esir_number', 'dup_trip_quad_code', 'function_code', 'portfolio_cost_method', 'interactive_portfolio_code']
df = drop_cols(df, drop_columns)

In [20]:
# 2. Map Booleans
bool_columns = ['receive_general_mailings', 'has_discrete_auth', 'is_non_objecting_beneficial_owner', 'is_objecting_to_disclose_info', 'consent_to_email_delivery', 'consent_to_pay_for_mail', 'has_received_instruction']
df = boolean_map(df, bool_columns)

In [21]:
# 3. Parse Times
time_columns = ['last_update_date']

df = parse_time(df, time_columns)

In [23]:
#

Looking for guidance on these columns
1. last_maintenance_user: A LOT of different users. Map to numbers?
2. retail_last_maintenance_user: Same as above
3. special_fee_code: numbers, characters, blanks
4. resp_specimen plan: numbers (like ids) and blanks

In [24]:
df.head()

,shareholder_language,special_tag,conjunction,title,tms_settlement_location,portfolio_name_address_option,portfolio_report_option,portfolio_summary_option,receive_general_mailings,loan_limit_override,...,has_discrete_auth,last_update_date,is_non_objecting_beneficial_owner,is_objecting_to_disclose_info,mailing_consent,consent_to_pay_for_mail,consent_to_email_delivery,has_received_instruction,risk_tolerance,investment_objective
0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1,NaN,...,0,0.000000,0,0,0.0,0,0,0,NaN,NaN
1,NaN,NaN,NaN,MR,NaN,0.0,0.0,0.0,1,NaN,...,0,0.953032,1,0,0.0,0,0,1,H10M90,B05G85S10
2,F,NaN,NaN,MADAME,NaN,0.0,0.0,0.0,1,NaN,...,0,0.538847,0,1,0.0,1,0,1,H50M50S00,G50S50
3,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1,NaN,...,0,0.870195,1,0,0.0,0,0,1,M99,G99
4,NaN,NaN,NaN,MRS,NaN,0.0,0.0,0.0,1,NaN,...,0,0.699648,0,1,0.0,0,0,1,M99,G99